version: "3.9"

services: 

  pyspark-notebook:
    image: kwnc/pyspark-notebook
    container_name: pyspark-notebook
    ports: 
      - "8888:8888"
    volumes:
      - spark-volume:/home/jovyan/work

volumes:
  spark-volume: